finish/src/Entity/Answer.php
<?php

namespace App\Entity;

use App\Repository\AnswerRepository;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;

/**
 * @ORM\Entity(repositoryClass=AnswerRepository::class)
 */
class Answer
{
    public const STATUS_NEEDS_APPROVAL = 'needs_approval';
    public const STATUS_SPAM = 'spam';
    public const STATUS_APPROVED = 'approved';

    use TimestampableEntity;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $username;

    /**
     * @ORM\Column(type="integer")
     */
    private $votes = 0;

    /**
     * @ORM\ManyToOne(targetEntity=Question::class, inversedBy="answers")
     * @ORM\JoinColumn(nullable=false)
     */
    private $question;

    /**
     * @ORM\Column(type="string", length=15)
     */
    private $status = self::STATUS_NEEDS_APPROVAL;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getVotes(): ?int
    {
        return $this->votes;
    }

    public function setVotes(int $votes): self
    {
        $this->votes = $votes;

        return $this;
    }

    public function getQuestion(): ?Question
    {
        return $this->question;
    }

    public function getQuestionText(): string
    {
        if (!$this->getQuestion()) {
            return '';
        }

        return (string) $this->getQuestion()->getQuestion();
    }

    public function setQuestion(?Question $question): self
    {
        $this->question = $question;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        if (!in_array($status, [self::STATUS_NEEDS_APPROVAL, self::STATUS_SPAM, self::STATUS_APPROVED])) {
            throw new \InvalidArgumentException(sprintf('Invalid status "%s"', $status));
        }

        $this->status = $status;

        return $this;
    }

    public function isApproved(): bool
    {
        return $this->status === self::STATUS_APPROVED;
    }
}

finish/src/Controller/AnswerController.php
<?php

namespace App\Controller;

use App\Entity\Answer;
use App\Repository\AnswerRepository;
use Doctrine\ORM\EntityManagerInterface;
use Psr\Log\LoggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class AnswerController extends AbstractController
{
    /**
     * @Route("/answers/popular", name="app_popular_answers")
     */
    public function popularAnswers(AnswerRepository $answerRepository, Request $request)
    {
        $answers = $answerRepository->findMostPopular(
            $request->query->get('q')
        );

        return $this->render('answer/popularAnswers.html.twig', [
            'answers' => $answers
        ]);
    }

    /**
     * @Route("/answers/{id}/vote", methods="POST", name="answer_vote")
     */
    public function answerVote(Answer $answer, LoggerInterface $logger, Request $request, EntityManagerInterface $entityManager)
    {
        $data = json_decode($request->getContent(), true);
        $direction = $data['direction'] ?? 'up';

        // use real logic here to save this to the database
        if ($direction === 'up') {
            $logger->info('Voting up!');
            $answer->setVotes($answer->getVotes() + 1);
            $currentVoteCount = rand(7, 100);
        } else {
            $logger->info('Voting down!');
            $answer->setVotes($answer->getVotes() - 1);
        }

        $entityManager->flush();

        return $this->json(['votes' => $answer->getVotes()]);
    }
}

finish/templates/answer/_answer.html.twig
<li class="mb-4">
    {% if showQuestion|default(false) %}
        <a
            href="{{ path('app_question_show', {
                slug: answer.question.slug
            }) }}"
            class="mb-1 link-secondary"
        >
            <strong>Question:</strong>
            {{ answer.questionText|u.truncate(80, '...') }}
        </a>
    {% endif %}
    <div class="row">
        <div class="col-1">
            <img src="{{ asset('images/tisha.png') }}" width="50" height="50" alt="Tisha avatar">
        </div>
        <div class="col-9">
            {{ answer.content|parse_markdown }}
            <p>-- {{ answer.username }}</p>
        </div>
        <div class="col-2 text-end">
            <small>{{ answer.createdAt|ago }}</small>
            <div
                class="vote-arrows"
                {{ stimulus_controller('answer-vote', {
                    url: path('answer_vote', {
                        id: answer.id
                    })
                }) }}
            >
                <button
                    class="vote-up btn btn-link"
                    name="direction"
                    value="up"
                    {{ stimulus_action('answer-vote', 'clickVote') }}
                ><i class="far fa-arrow-alt-circle-up"></i></button>
                <button
                    class="vote-down btn btn-link"
                    name="direction"
                    value="down"
                    {{ stimulus_action('answer-vote', 'clickVote') }}
                ><i class="far fa-arrow-alt-circle-down"></i></button>
                <span><span {{ stimulus_target('answer-vote', 'voteTotal') }}>{{ answer.votes }}</span></span>
            </div>
        </div>
    </div>
</li>

finish/templates/answer/popularAnswers.html.twig
{% extends 'base.html.twig' %}

{% block title %}Popular Answers{% endblock %}

{% block body %}
<div class="container my-md-4">
    <div class="d-flex justify-content-between">
        <h1>Most Popular Answers</h1>

        <form action="{{ path('app_popular_answers') }}">
            <input
                type="search"
                name="q"
                value="{{ app.request.query.get('q') }}"
                class="form-control"
                placeholder="Search..."
                aria-label="Search"
            >
        </form>
    </div>

    <ul class="list-unstyled">
        {% for answer in answers %}
            {{ include('answer/_answer.html.twig', {
                showQuestion: true
            }) }}
        {% endfor %}
    </ul>
</div>
{% endblock %}